import TopNav from "@/shared/components/TopNav";
import "./globals.css";
import Navbar from "@/shared/components/Navbar";
import Footer from "@/shared/components/Footer";

export const metadata = {
  title: "Digital Marketing",
  description: "Generated by paperlesssoft",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        <Navbar />
        {children}
        <Footer />
      </body>

    </html>
  );
}
